const menu = [
  { name: "Ensalada de espinacas", price: 450, category: "Appetizers" },
  { name: "Ceviche de pescado", price: 680, category: "Appetizers" },
  { name: "Tostadas de chorizo", price: 350, category: "Appetizers" },
  { name: "Croquetas de pollo", price: 400, category: "Appetizers" },
  { name: "Patatas bravas", price: 300, category: "Appetizers" },
  { name: "Pan con tomate", price: 200, category: "Appetizers" },
  { name: "Aceitunas aliñadas", price: 250, category: "Appetizers" },
  { name: "Choripán", price: 500, category: "Appetizers" },
  { name: "Provolone", price: 350, category: "Appetizers" },
  { name: "Morcilla", price: 450, category: "Appetizers" },
  { name: "Milanesa de carne", price: 850, category: "MainCourses" },
  { name: "Pescado al horno", price: 1200, category: "MainCourses" },
  { name: "Fettuccine Alfredo", price: 900, category: "MainCourses" },
  { name: "Asado de tira", price: 1000, category: "MainCourses" },
  { name: "Churrasco", price: 950, category: "MainCourses" },
  { name: "Pollo al curry", price: 800, category: "MainCourses" },
  { name: "Arroz con mariscos", price: 1100, category: "MainCourses" },
  { name: "Tortellini de carne", price: 950, category: "MainCourses" },
  { name: "Canelones de espinacas", price: 900, category: "MainCourses" },
  { name: "Choripán de parrilla", price: 700, category: "MainCourses" },
  { name: "Torta de chocolate", price: 400, category: "Desserts" },
  { name: "Helado de vainilla", price: 250, category: "Desserts" },
  { name: "Flan de dulce de leche", price: 300, category: "Desserts" },
  { name: "Cheesecake", price: 450, category: "Desserts" },
  { name: "Tiramisú", price: 400, category: "Desserts" },
  { name: "Mousse de chocolate", price: 350, category: "Desserts" },
  { name: "Crema catalana", price: 300, category: "Desserts" },
  { name: "Torta de ricotta", price: 400, category: "Desserts" },
  { name: "Gelato de frutas", price: 250, category: "Desserts" },
  { name: "Brownie", price: 300, category: "Desserts" },
  { name: "Cerveza artesanal", price: 500, category: "Drinks" },
  { name: "Jugo de naranja", price: 200, category: "Drinks" },
  { name: "Vino tinto", price: 600, category: "Drinks" },
  { name: "Café espresso", price: 150, category: "Drinks" },
  { name: "Cocktail de frutas", price: 700, category: "Drinks" },
  { name: "Agua mineral", price: 100, category: "Drinks" },
  { name: "Cerveza negra", price: 550, category: "Drinks" },
  { name: "Té herbal", price: 120, category: "Drinks" },
  { name: "Whisky escocés", price: 800, category: "Drinks" },
  { name: "Refresco de cola", price: 180, category: "Drinks" },
];

export default menu;
